# Vendor: NEC Corporation.
# Product: WebOTX Operator for Kubernetes
# Version: 10.40.00.00
# 
apiVersion: v1
kind: ConfigMap
metadata:
  name: webotx-operator-config
data:
  LOG_LEVEL: "INFO"
  LOG_ROTATION: "5"
  LOG_FILESIZE: "1"
  PPROF_ENABLED: "FALSE"
  PPROF_INTERVAL: "10"
  PPROF_ROTATION: "144"
  METERING_ENABLED: "TRUE"
  METERING_INTERVAL: "1"
  METERING_TIMEOUT_SCRAPE: "10"
  METERING_TIMEOUT_READ: "60"
  METERING_TIMEOUT_WRITE: "30"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webotx-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webotx-operator
  template:
    metadata:
      labels:
        name: webotx-operator
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8383"
    spec:
      # Set when pulling an image from the private registry.
      #imagePullSecrets:
      #  - name: REPLACE_REGISTRY_AUTH_SECRET_NAME
      serviceAccountName: webotx-operator
      volumes:
        - name: share-volume
          emptyDir: {}
        # Set when replacing the server certificate used by the metering function.
        #- name: certificate-volume
        #  configMap:
        #    name: REPLACE_CERTIFICATE_CONFIGMAP_NAME
      containers:
        - name: webotx-operator
          # Replace this with the built image name
          image: REPLACE_WEBOTX_OPERATOR_IMAGE
          command:
          - /opt/WebOTX/bin/entrypoint
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "webotx-operator"
            - name: LICENSE_KEY
              # Replace this with the WebOTX Operator License Key
              value: REPLACE_LICENSE_KEY
          envFrom:
            - configMapRef:
                name: webotx-operator-config
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8686
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: share-volume
              mountPath: /opt/WebOTX/logs
              subPath: logs
            - name: share-volume
              mountPath: /opt/WebOTX/profile
              subPath: profile
            # Set when replacing the server certificate used by the metering function.
            #- mountPath: /opt/WebOTX/config/server.crt
            #  name: certificate-volume
            #  subPath: server.crt
            #- mountPath: /opt/WebOTX/config/server.key
            #  name: certificate-volume
            #  subPath: server.key
